// <auto-generated />
import About from './pages/About.svelte';
import Index from './pages/Index.svelte';
import {RouteData} from 'svelte-dotnet';

export const routes = {
    '/{counter:int?}': new RouteData(Index),
    '/about': new RouteData(About)
}