// <auto-generated />
import IndexLayout from './layouts/IndexLayout.svelte';
import About from './pages/About.svelte';
import Index from './pages/Index.svelte';
import Users from './pages/Users.svelte';
import {RouteData} from 'svelte-dotnet';

export const routes = {
    '/{counter:double?}': new RouteData(Index, IndexLayout),
    '/about': new RouteData(About),
    '/users': new RouteData(Users),
    '/users/{skip}': new RouteData(Users)
}