// <auto-generated />
import SignInLayout from './layouts/SignInLayout.svelte';
import Counter from './pages/Counter.svelte';
import FetchData from './pages/FetchData.svelte';
import Index from './pages/Index.svelte';
import ServerSideData from './pages/ServerSideData.svelte';
import SignIn from './pages/SignIn.svelte';
import {RouteData} from 'svelte-dotnet';

export const routes = {
    '/': new RouteData(Index),
    '/counter/{initial:int?}': new RouteData(Counter),
    '/fetchdata': new RouteData(FetchData),
    '/server': new RouteData(ServerSideData),
    '/signin': new RouteData(SignIn, SignInLayout)
}