// <auto-generated />
import Index from './pages/Index.svelte';
import About from './pages/About.svelte';
import {RouteData} from "./lib";
import IndexLayout from "./shared/IndexLayout.svelte";

export const routes: Record<string, RouteData> = {
    '/': new RouteData(Index, IndexLayout),
    '/about': new RouteData(About)
};